### PR TITLE
update runtime, cups, and gtk

### LINKED ISSUE #7: Info: runtime org.freedesktop.Platform branch 21.08 is end-of-life, with reason:
Info: runtime org.freedesktop.Platform branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   com.simplenote.Simplenote

### PR DESCRIPTION
**Pull request by mfschumann**
fixes flathub/com.simplenote.Simplenote#7

### CODE REVIEW

**Comment by hanny00** [comment]
I saw your Pullrequest and want to install the testing build, but
~ ❯❯❯ flatpak install --user https://dl.flathub.org/build-repo/56561/com.simplenote.Simplenote.flatpakref
Fehler: Can't load uri https://dl.flathub.org/build-repo/56561/com.simplenote.Simplenote.flatpakref: Server returned status 404

**Comment by mfschumann** [comment]
I think test builds are automatically deleted after a while. I will generate a new test build for you to test.

**Comment by mfschumann** [comment]
bot, build

**Comment by mfschumann** [comment]
@hanny00 Here you go.

**Comment by hanny00** [comment]
Seems to be, that it works, i hope tomorror too, if i am on my main pc, when will you push it to stable?

**Comment by mfschumann** [comment]
I cannot merge since I am not the maintainer.
@rhjhunt Would you mind to merge this PR?

**Review by carestad — APPROVED** [review]

**Comment by carestad** [comment]
> I cannot merge since I am not the maintainer. @rhjhunt Would you mind to merge this PR?

Seems he hasn't been active on Github in a while. But looking at #4, maybe an approval from a reviewer is enough to be allowed to merge it yourself? I gave it a go at least :slightly_smiling_face:

**Comment by mfschumann** [comment]
No dice. @barthalion Would you mind to merge this PR? The maintainer seems to be inactive.

**Pull request merged**
